### ISSUE TITLE
Drupal core bug: Uninstalling a module providing display extenders causes fatal errors

### ISSUE THREAD

**Issue by dpi** [dpi/views_advanced_routing#1]
Link to bug potentially impacting this module [Uninstalling a module providing display extenders causes fatal errors](https://www.drupal.org/node/2635728)

**Comment by GH2703** [comment]
I had encountered this WSOD problem several times upon uninstalling this module until I read the instruction on d.o about enabling Views Advanced Routing.

```
Enable the module.
Go to Administration -> Structure -> Views
Click the 'Settings' tab.
Click the 'Advanced' sub tab.
Under Display extenders, enable the 'Route' checkbox.
```

I then unchecked the 'Route' checkbox and uninstalled again.  This time it went through nicely.

**Comment by dpi** [comment]
Moved to https://www.drupal.org/project/views_advanced_routing/issues/3164993
