### ISSUE TITLE
The configuration property display.page_day.display_options.display_extenders.views_advanced_routing_route.route.options.parameters.node.type doesn't exist

### ISSUE THREAD

**Issue by heddn** [dpi/views_advanced_routing#3]
341   24/Jul 07:25   php      Error      InvalidArgumentException: The configuration property                  
                                           display.page_day.display_options.display_extenders.views_advanced_ro  
                                           uting_route.route.options.parameters.node.type doesn't exist. in      
                                           Drupal\Core\Config\Schema\ArrayElement->get() (line 76 of             
                                           /var/www/html/web/core/lib/Drupal/Core/Config/Schema/ArrayElement.ph  
                                           p).  

Getting the error on 8.6.x. From reviewing the schema, the error is accurate.

**Comment by dpi** [comment]
Moving schema related issues to https://www.drupal.org/project/views_advanced_routing/issues/3102832
